{
 "title": "Stress Levels",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Stress Level",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "$tag_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "2",
     "measurement": "flink_events",
     "query": "SELECT last(\"stressLevel\") FROM \"flink_events\" WHERE $timeFilter GROUP BY time($__interval), \"id\"::tag fill(null)",
     "select": [
      [
       { "params": [ "stressLevel" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heart Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "targets": [
    {
     "alias": "$tag_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flink_events",
     "query": "SELECT last(\"HR\") FROM \"flink_events\" WHERE $timeFilter GROUP BY time($__interval), \"id\"::tag fill(null)",
     "select": [
      [
       { "params": [ "HR" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$tag_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flink_events",
     "query": "SELECT last(\"TEMP\") FROM \"flink_events\" WHERE $timeFilter GROUP BY time($__interval), \"id\"::tag fill(null)",
     "select": [
      [
       { "params": [ "TEMP" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Electrodermal Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "μS" } },
   "targets": [
    {
     "alias": "$tag_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "id::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flink_events",
     "query": "SELECT last(\"EDA\") FROM \"flink_events\" WHERE $timeFilter GROUP BY time($__interval), \"id\"::tag fill(null)",
     "select": [
      [
       { "params": [ "EDA" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}